BlogApp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
   
    path("user/", include("user.urls", namespace="user")),
    path("accounts/",include('django.contrib.auth.urls')),
    path("",include("myblog.urls",namespace="myblog")),
    path('api-auth/', include('rest_framework.urls')),
    path("blog_api/",include("blog_api.urls",namespace="blog_api")),
    # path("fedility_service/",include("fedility_service.urls",namespace="fedility_service")),

]


urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/urls.py
from django.urls import path
from myblog import views


app_name = "myblog"

urlpatterns = [
    path("", views.home_view, name="home"),
    # path("",views.list_view,name="home"),
    path("list",views.list_view,name="list"),
    # path('<slug:slug>/',views.detail_view,name="detail"),
    path("<int:aid>/",views.detail_view,name="detail"),
    path("create",views.create_view,name="create"),
    # path('like/',views.user_like_post,name="user_like_post"),
    path('like/',views.like_post,name="like-post"),
    path('contact',views.contact_view,name="contact"),

    
    
]

user/urls.py
from django.urls import path
from user import views
from django.contrib.auth import views as auth_views
# from django.urls import url 

app_name="user"
urlpatterns=[
    
path("register/",views.signup,name="register"),
path("login/",views.login_page,name="login"),
path("list/",views.Userview,name="list"),
path("post_data/",views.post_Userdata,name="post"),
path("<int:id>/",views.post_userdetail,name="user_detail"),


    #reset-password urls
path("accounts/password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"),
path("accounts/password_reset/done/", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
path("accounts/reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
path("accounts/reset/done/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),

]

myblog/models.py
from django.db import models
from django.contrib.auth import get_user_model

USER = get_user_model()

# Create your models here.
STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Article(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    author = models.ForeignKey(USER, on_delete= models.CASCADE,related_name='blog_posts')
    image = models.ImageField(upload_to="myblog/image", default="default/blog.png")
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(USER, related_name='likes',blank=True,default=None)

   

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title
    @property
    def num_likes(self):
        return self.likes.all().count()

Like_Choices=(
    ('Like','Like'),
    ('Unlike','Unlike')
)

class Like(models.Model):
    user=models.ForeignKey(USER, on_delete= models.CASCADE)
    article=models.ForeignKey(Article, on_delete= models.CASCADE)
    value=models.CharField(choices=Like_Choices,default='Like',max_length=10)
    # def __str__(self):
    #     return self.article

class Comment(models.Model): 
    post = models.ForeignKey(Article,on_delete=models.CASCADE,related_name='comments')
    # name = models.CharField(max_length=80) 
    # email = models.EmailField()
    user=models.ForeignKey(USER, on_delete= models.CASCADE) 
    body = models.TextField() 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    active = models.BooleanField(default=True) 

    class Meta: 
        ordering = ('created',) 

    def __str__(self): 
        return 'Comment by {} on {}'.format(self.user,self.post) 

class Contact(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField()
    message=models.TextField()


    def __str__(self):
        return self.name

myblog/forms.py
from django import forms
from myblog.models import Article,Comment,Contact


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","slug","author", "image", "content","status"]



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('user', 'body')


class ContactForm(forms.ModelForm):
    class Meta:
        model= Contact
        fields=('name','email','message')

myblog/views.py
from django.contrib.auth import get_user_model
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render

from myblog.forms import ArticleForm, CommentForm, ContactForm
from myblog.models import Article, Comment, Like
import json
from django.core import serializers


USER = get_user_model()

def home_view(request):
    # user1 = USER.objects.all()
    # user = USER.objects.get('username
    
    articles=Article.objects.filter(status=1).order_by('-created_on')
    context={"articles":articles
    # "user":user
    }
    template_name="myblog/index.html"
    return render(request,template_name,context)

def list_view(request):
    user = USER.objects.get(username=request.user.username)
    print("//////",user)
    articles=Article.objects.filter(status=1,author=user).order_by('-created_on')
    
    template_name="myblog/list.html"
    context={"articles":articles
    }
    return render(request,template_name,context)

def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


def detail_view(request,aid):
    print("haiiiiiiiiii")
    articles=get_object_or_404(Article,pk=aid)

    comments = articles.comments.filter(active=True)
    
    new_comment = None
    # comment_form=CommentForm()
    # if request.method == 'POST':
    if is_ajax(request):
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet          
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = articles
            # Save the comment to the database
            new_comment.save()
            return JsonResponse({
                
                'msg':'Success',
                  'new_comment': new_comment.body,
                 
                  'date':new_comment.created,
                #   'new_comment':new_comment
            })
    else:
        comment_form = CommentForm() 
        
    
    
    template_name="myblog/detail.html"
    context={
        "articles":articles,
       'comments': comments,
    'new_comment': new_comment,
    'comment_form': comment_form
    
    }
    return render(request,template_name,context)
    

def like_post(request):
   
    user = USER.objects.get(username=request.user.username)
   
    print("...............",user)
    # if request.method=='POST':
    #     article_id=request.POST.get('article_id')
    #     print("idddddddd.....",article_id)
    #     aricle_obj=Article.objects.get(id=article_id)

    #     if user in aricle_obj.likes.all():
    #         aricle_obj.likes.remove(user)
    #     else:
    #         aricle_obj.likes.add(user)
    # like,created=Like.objects.get_or_create(user=user,article_id=article_id)
    # if not created:
    #     if like.value=='Like':
    #         like.value='UnLike'
    #     else:
    #         like.value='Like'
    # like.save()

    # # return redirect('myblog:detail', kwargs={'article_id': article_id})
    # return JsonResponse({
    #            'msg':'Success'
    #        })

    if is_ajax(request):
        article_id=request.POST.get('article_id')
        print("idddddddd.....",article_id)
        aricle_obj=Article.objects.get(id=article_id)

        if user in aricle_obj.likes.all():
            aricle_obj.likes.remove(user)
        else:
            aricle_obj.likes.add(user)
    like,created=Like.objects.get_or_create(user=user,article_id=article_id)
    if not created:
        if like.value=='Like':
            like.value='UnLike'
        else:
            like.value='Like'
    like.save()
    return JsonResponse({
                'msg':'Success',
                'article_id':article_id,
                  "likes_count":aricle_obj.likes.all().count()
              
            })




def create_view(request):
    context ={}
    form = ArticleForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('myblog:home')
          
    context['form']= form
    return render(request, "myblog/create.html", context)



def contact_view(request):
    form=ContactForm()
    # if request.method == 'POST':
    #     form=ContactForm(request.POST)
    #     if form.is_valid():
    #         form.save()
    #         return redirect('myblog:contact')
    if is_ajax(request):
        form=ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return JsonResponse({
                'msg':'Success'
            })
    return render(request,'myblog/contact.html',{'form':form})

templates/myblog/contact.html
{% extends "base.html" %} {% block content %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact</title>
</head>
<body>
    <a href="{% url 'myblog:home'  %}"class="btn btn-info">Back</a>

<script src="https://code.jquery.com/jquery-3.5.0.min.js"integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous">
</script>




<div class="container" style="max-width: 600px">
  <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Contact</h1>
  </div>
    <div class="py-5">
        <div class="row">
          <div class="col-12">
            <div class="card mb-4">
                <div class="card-body">
                    <form method="post" id="form">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>
    
    <script>
      const form=document.getElementById('form');
       form.addEventListener("submit",submitHandler);
      
    
       function submitHandler(e){
        e.preventDefault();
        $.ajax({
              type:'POST',
              url:"{% url 'myblog:contact' %}",
              data:$("#form").serialize(),
              dataType:'json',
              success:function(data){ 
              if(data.msg === 'Success'){
                  form.reset(); 
                  alert('Form is submitted.')
            }
         }
    
      }) 
    
      }
    </script>
</body>
</html>

{% endblock %}

templates/myblog/create.html
{% extends "base.html" %} {% block content %}


<a href="{% url 'myblog:home'  %}"class="btn btn-info">Back</a>


<div class="container" style="max-width: 600px">
  <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Article | <span class="text-primary h4">ADD</span></h1>
  </div>
  <div class="py-5">
    <div class="row">
      <div class="col-12">
        <div class="card mb-4">
            <div class="card-body">
             
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %} 
          {% if info %}
          <p class="text-primary">{{info}}</p>
          {% endif %} {{ form.as_p }}
          <input type="submit" value="Submit">
        </form>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/myblog/detail.html
{% extends 'base.html' %} {% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>BLOGAPP|DETAIL </title>
  
  
</head>
<body>

  <script src="https://code.jquery.com/jquery-3.5.0.min.js"integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous">
  </script>
  



  <div class="container">
    <a href="{% url 'myblog:home'  %}"class="btn btn-info">Back</a>
    <div class="row">
      <div class="col-md-8 card mb-4  mt-3 left  top">
        <div class="card-body">
          <!-- <img src="{{myblog.image.url}}" alt="..."  /> -->
          <div class="card-body">
            <h5 class="card-title">{{ articles.title }}</h5>
            <p class="card-text">{{ articles.author }} | {{ articles.created_on }}</p>
            <p class="card-text">{{ articles.content | safe }}</p>
            <p class="card-text text-muted fst-italic"> 
              
           <form action="{% url 'myblog:like-post' %}" method="post"class="btn like-form"> 
          <!-- <form action="" method="post"class="btn"></form> -->
            {% csrf_token %}
            <input type="hidden" name="article_id" value="{{ articles.id }}" >
            {% if user not in articles.likes.all %}
              <button  type="submit" id="btn_like" class="like" value="{{ articles.id }}" name="article_id" >Like</button>
            {% else %}
              <button  type="submit" id="btn_like" class="like" value="{{ articles.id }}"  name="article_id">UnLike</button>
            {% endif %}
            <span id="like-count"> {{ articles.likes.all.count }} likes</span>
           </form>
           
  
          <!-- <strong class="like_count">{{ articles.likes.all.count }} Likes</strong> -->
  
          {% for comment in comments %}
            <div class="comment" id="comn">
            <!-- <p class="info" >
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}

              
            </p>
            {{ comment.body|linebreaks }} -->
            <h5 class="mt-0" id = 'commenter'>comment by {{comment.user}}</h5>
            <p id = 'comment'>{{comment.body}}</p>
            </div>
          {% empty %}
            <p>There are no comments yet.</p>
          {% endfor %}
  
          {% if new_comment %}
            <h2>Your comment has been added.</h2>
          {% else %}
            <h2>Add a new comment</h2>
            <form action="" method="post" id="form">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
            </form>
          {% endif %}
          
        </div>
      </div>
    
    </div>
  </div>
  



<script>
// comment ajax_form
const form=document.getElementById('form');
let commentContainer = document.getElementById('comn')
console.log(form)
form.addEventListener("submit",submitHandler);
      
    
       function submitHandler(e){
        e.preventDefault();
        let commenter = document.createElement('h5')
        let comment = document.createElement('p')
        commenter.classList.add('mt-0')
        $.ajax({
              type:'POST',
             
             data:$("#form").serialize(),
              dataType:'json',
              success:function(data){ 
                console.log(data);
              commenter.innerText = data.author
              comment.innerText = data.new_comment
              commentContainer.appendChild(commenter)
              commentContainer.appendChild(comment)
              form.reset()

            
         }
    
      }) 
    
      }
    

$(document).ready(function(){

//like ajax call
$('.like-form').submit(function(e){
    e.preventDefault();
     const article_id=$('.like').val();
    
     console.log(article_id);
     const token=$('input[name=csrfmiddlewaretoken]').val();
     const url=$(this).attr('action') 
  
   $.ajax({
       method:"POST",
       url:url,
       headers:{'X-CSRFToken': token},
       data:{
           'article_id':article_id
       },
       success:function(response){
        console.log(response);
         if(response.msg === 'Success'){
          const btn= document.getElementById("btn_like");
          var btn_like= document.getElementById("like-count");
           var count=response.likes_count
           btn_like.innerText=count;
          console.log(btn);
          console.log(count);
         

    if(btn.innerText === "Like"){
      btn.innerText = "UnLike";
    
     btn_like.innerText=count;
      }
      else{
        btn.innerText= "Like";
        
        btn_like.innerText=count;
       
        }
       
                    }

                   
      
   
  }}

)})})


</script>

   





</body>
</html>


{% endblock %}

templates/myblog/index.html
{% extends 'base.html' %}
{% block title %} home{% endblock%}
{% block content %}
{% load static%}




<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>BLOGAPP</title>
  <meta content="" name="description">
  <meta content="" name="keywords">
  

 </head>

<body>

  <!-- ======= Top Bar ======= -->
  <section id="topbar" class="d-flex align-items-center">
   
    <div  style="width:100%;">
      <!-- <ul class="navbar nav_inline" > -->
  {% if user.is_authenticated %}
  <div class="div_inline">
  
    <a class="nav-link scrollto" href="#profile">{{user}}  </a>
    <span>|</span>
    <a  class="nav-link scrollto" href="{% url 'logout' %}">Logout</a>
  
  </div>
        {% endif %}
        <!-- </ul> -->
        </div>
</section>

  <!-- ======= Header ======= -->
  <header id="header" class="d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <h1 class="logo"><a href="index.html">BLOGAPP<span>.</span></a></h1>
      

      <nav id="navbar" class="navbar">
        <ul>
          
          
          <!-- <li><a class="nav-link scrollto" href="#contact">Contact</a></li> -->
           
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link scrollto" href="{% url 'myblog:list' %}">Article</a></li>
            <li>
            <a class="nav-link scrollto" href="{% url 'myblog:create' %}">Add Article</a>

          
          </li>
          
          
         
           {% else %} 
          <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
          <li class="nav-item">
            <a class="nav-link scrollto" href="{% url 'login' %}">signin</a>
          
          </li>
          <li class="nav-item">
            <a class="nav-link scrollto" href="{% url 'user:register' %}">Signup</a>
          
          </li>
          <li class="nav-item">
            <a class="nav-link scrollto" href="{% url 'myblog:contact' %}">Contact</a>
          
          </li>
          

          {% endif %} 
         
          
         
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  

  <section id="hero" class="d-flex align-items-center">
    <div class="container" data-aos="zoom-out" data-aos-delay="100">
      
      <div class="d-flex">
        <a href="#about" class="btn-get-started scrollto">Get Started</a>
      </div>
    </div>
  </section><!-- End Hero -->

    
<section>
  {% if not  user.is_authenticated %}

  <div class="container">
    <div class="row">
        
        <div class="col-md-8 mt-3 left">
            {% for article in articles %}
            <div class="card mb-4">
                <div class="card-body">
                 
                    <h2 class="card-title">{{ article.title }}</h2>
                    <p class="card-text text-muted h6">{{ article.author }} | {{ article.created_on}} </p>
                    <p class="card-text">{{article.content|slice:":200" }}</p>
                    {% if user.is_authenticated %}
                    <a href="{% url 'myblog:detail'  article.id  %}" class="btn btn-primary">Read More &rarr;</a>
                    
                    {% else %}
                    <a href="{% url 'login' %}?next={% url 'myblog:detail'  article.id  %}" class="btn btn-primary">Read More &rarr;</a>
                    {% endif %}
                    <strong>{{ article.likes.all.count }} Likes</strong>
                </form>
              </div>
            </div>
            {% endfor %}
        </div> 

        
       {% endif %} 
</section>
  

   

    
            <div class="container py-4">
      <div class="copyright">
        &copy; Copyright <strong><span>BLOGAPP</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        
        Designed by <a href="https://bootstrapmade.com/">Chinju Meina Monachan</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  {% endblock %}

</body>

</html>

templates/myblog/list.html
{% extends "base.html" %} 
{% load static %}
{% block content %}
{% load static %}
<div class="container">
  <a href="{% url 'myblog:home'  %}"class="btn btn-info">Back</a>
                  
  <div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for article in articles %}
            <div class="card mb-4">
                <div class="card-body">
                    <img src="{{article.image.url}}" alt="..." class="card-img-top" />
                    <h2 class="card-title">{{ article.title }}</h2>
                    <p class="card-text text-muted h6">{{ article.author }} | {{ article.created_on}} </p>
                    <p class="card-text">{{article.content|slice:":200" }}</p>
                    {% if user.is_authenticated %}
                    <a href="{% url 'myblog:detail'  article.id  %}" class="btn btn-primary">Read More &rarr;</a>
                    
                    {% else %}
                    <a href="{% url 'login' %}?next={% url 'myblog:detail'  article.id  %}" class="btn btn-primary">Read More &rarr;</a>
                    {% endif %}
                    <strong>{{ article.likes.all.count }} Likes</strong>
    
                    </form>
                    
                  </div>
                </div>
            {% endfor %}
        </div>
        </div>
        
        </div> 
    </div>  

   
            
       
    </div>
    </div>
    

          {% endblock %}
          